/**
 * ─────────────────────────────────────────────────────────────────
 * Intently PIM · seed script
 *
 * Idempotent. Creates:
 *   - one admin user (from ADMIN_EMAIL / ADMIN_PASSWORD env)
 *   - one default sales channel + region + currency
 *   - the products listed in ./seed-products.json (generated by
 *     scripts/build-seed.mjs from the Kaggle styles.csv metadata)
 *
 * Each product carries metadata.intentlyId = `k{kaggleId}` so the enrichment
 * layer keys vectors by the SAME id the discovery river uses — that's what
 * lets a vector hit map back to a renderable Product (the PIM→discovery seam).
 *
 * Run via:
 *   npx medusa exec ./src/scripts/seed-kaggle.ts
 *   (also invoked by start.sh on container boot)
 * ─────────────────────────────────────────────────────────────────
 */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { ExecArgs } from '@medusajs/framework/types'
import {
  ContainerRegistrationKeys,
  Modules,
  ProductStatus,
} from '@medusajs/framework/utils'
import {
  createApiKeysWorkflow,
  createProductCategoriesWorkflow,
  createProductsWorkflow,
  createRegionsWorkflow,
  createSalesChannelsWorkflow,
  createStockLocationsWorkflow,
  createUserAccountWorkflow,
  linkSalesChannelsToApiKeyWorkflow,
} from '@medusajs/medusa/core-flows'

interface KaggleRow {
  id: number
  gender: string
  masterCategory: string
  subCategory: string
  articleType: string
  baseColour: string
  season: string
  year: number
  usage: string
  productDisplayName: string
}

// Generated by scripts/build-seed.mjs. Read from disk (not imported) so the
// medusa-exec runtime doesn't have to resolve a JSON module.
const SEED_FILE = resolve(process.cwd(), 'src', 'scripts', 'seed-products.json')
const PRODUCTS: KaggleRow[] = JSON.parse(readFileSync(SEED_FILE, 'utf8'))

const BATCH_SIZE = 50

function handleFor(row: KaggleRow): string {
  return `kaggle-${row.id}`
}

/** The river-aligned id the enrichment layer keys vectors by. */
function intentlyIdFor(row: KaggleRow): string {
  return `k${row.id}`
}

function describeFor(row: KaggleRow): string {
  return [
    row.productDisplayName,
    `${row.gender} ${row.usage} ${row.articleType}.`,
    `Category: ${row.masterCategory} > ${row.subCategory}.`,
    `Colour: ${row.baseColour}. Season: ${row.season}. ${row.year}.`,
  ].join(' ')
}

/**
 * Image URL the seed records. Pictures are absent until a new bank is chosen;
 * these URLs 404 in the interim (expected). Override base with
 * PIM_IMAGE_BASE_URL; default points at the Next app's /catalog.
 */
function imageUrlFor(row: KaggleRow): string {
  const base = process.env.PIM_IMAGE_BASE_URL || 'http://localhost:3000/catalog'
  return `${base}/${row.id}.webp`
}

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = []
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size))
  return out
}

// Decimal EUR prices by article type. Medusa v2 stores prices as-is, NOT in
// cents (49.99 = €49.99) — so these are plain euros, not 4900.
const PRICE_BY_ARTICLE: Record<string, number> = {
  Dresses: 49.99, Jackets: 89.99, Shirts: 34.99, Tops: 19.99, Skirt: 39.99,
  Trousers: 44.99, Backpacks: 29.99, Caps: 14.99, Sunglasses: 24.99,
}
function priceFor(row: KaggleRow): number {
  return PRICE_BY_ARTICLE[row.articleType] ?? 29.99
}

// Storefront browse categories. articleType → category name.
const CATEGORY_BY_ARTICLE: Record<string, string> = {
  Dresses: 'Dresses', Tops: 'Tops', Shirts: 'Shirts', Skirt: 'Skirts',
  Trousers: 'Trousers', Jackets: 'Outerwear', Backpacks: 'Bags',
  Caps: 'Accessories', Sunglasses: 'Accessories',
}

export default async function seed({ container }: ExecArgs) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const productModule = container.resolve(Modules.PRODUCT)
  const salesChannelModule = container.resolve(Modules.SALES_CHANNEL)

  logger.info(`Seed source: ${SEED_FILE} (${PRODUCTS.length} products)`)

  // ── 1. Admin user ──────────────────────────────────────────────
  const adminEmail = process.env.ADMIN_EMAIL || 'admin@intently.local'
  const adminPassword = process.env.ADMIN_PASSWORD || 'supersecret'
  try {
    await createUserAccountWorkflow(container).run({
      input: {
        authIdentityId: '', // workflow generates if empty
        userData: {
          email: adminEmail,
          first_name: 'Intently',
          last_name: 'Admin',
        },
      },
    })
    logger.info(`Created admin user ${adminEmail} (password: ${adminPassword})`)
  } catch (err) {
    logger.info(
      `Admin user ${adminEmail} likely already exists; skipping: ${(err as Error).message}`,
    )
  }

  // ── 2. Sales channel + region ──────────────────────────────────
  let salesChannel = (await salesChannelModule.listSalesChannels({
    name: 'Default Sales Channel',
  }))[0]
  if (!salesChannel) {
    const { result } = await createSalesChannelsWorkflow(container).run({
      input: {
        salesChannelsData: [{ name: 'Default Sales Channel' }],
      },
    })
    salesChannel = result[0]
    logger.info('Created default sales channel')
  } else {
    logger.info('Default sales channel already present')
  }

  try {
    await createRegionsWorkflow(container).run({
      input: {
        regions: [
          {
            name: 'Europe',
            currency_code: 'eur',
            countries: ['fi', 'gb', 'de', 'fr', 'es', 'it', 'nl', 'se', 'no', 'dk'],
            payment_providers: ['pp_system_default'],
          },
        ],
      },
    })
    logger.info('Created Europe region')
  } catch (err) {
    logger.info(`Region likely already exists: ${(err as Error).message}`)
  }

  try {
    await createStockLocationsWorkflow(container).run({
      input: {
        locations: [{ name: 'Default Warehouse' }],
      },
    })
  } catch {
    // already exists
  }

  // ── 3. Publishable API key linked to sales channel ─────────────
  // The intently/ Next.js app reads via the Store API; v2 requires this
  // header. We create one and log the value so setup surfaces it.
  try {
    const { result: keys } = await createApiKeysWorkflow(container).run({
      input: {
        api_keys: [
          {
            title: 'Intently storefront',
            type: 'publishable',
            created_by: '',
          },
        ],
      },
    })
    await linkSalesChannelsToApiKeyWorkflow(container).run({
      input: {
        id: keys[0].id,
        add: [salesChannel.id],
      },
    })
    logger.info(`Publishable key: ${keys[0].token}`)
    logger.info(
      `→ set MEDUSA_PUBLISHABLE_KEY=${keys[0].token} in intently/.env.local`,
    )
  } catch (err) {
    logger.info(
      `Publishable key likely already exists: ${(err as Error).message}`,
    )
  }

  // ── 3b. Product categories (storefront browse nav) ────────────
  const desiredCats = [...new Set(Object.values(CATEGORY_BY_ARTICLE))]
  const existingCats = await productModule.listProductCategories(
    { name: desiredCats },
    { take: desiredCats.length },
  )
  const catIdByName = new Map<string, string>(existingCats.map((c) => [c.name, c.id]))
  const catsToCreate = desiredCats.filter((n) => !catIdByName.has(n))
  if (catsToCreate.length) {
    const { result: createdCats } = await createProductCategoriesWorkflow(container).run({
      input: {
        product_categories: catsToCreate.map((name) => ({ name, is_active: true })),
      },
    })
    for (const c of createdCats) catIdByName.set(c.name, c.id)
    logger.info(`Created categories: ${catsToCreate.join(', ')}`)
  } else {
    logger.info('Product categories already present')
  }

  // ── 4. Products ───────────────────────────────────────────────
  // Idempotent at the product level (handles like `kaggle-15970`).
  const existing = await productModule.listProducts(
    { handle: PRODUCTS.map(handleFor) },
    { take: PRODUCTS.length },
  )
  const existingHandles = new Set(existing.map((p) => p.handle))

  const toCreate = PRODUCTS.filter((row) => !existingHandles.has(handleFor(row)))
  if (toCreate.length === 0) {
    logger.info(`All ${PRODUCTS.length} products already present; nothing to create`)
    return
  }

  const batches = chunk(toCreate, BATCH_SIZE)
  let created = 0
  for (let i = 0; i < batches.length; i++) {
    const batch = batches[i]
    await createProductsWorkflow(container).run({
      input: {
        products: batch.map((row) => ({
          title: row.productDisplayName,
          handle: handleFor(row),
          status: ProductStatus.PUBLISHED,
          description: describeFor(row),
          thumbnail: imageUrlFor(row),
          images: [{ url: imageUrlFor(row) }],
          options: [{ title: 'Default', values: ['default'] }],
          variants: [
            {
              title: 'Default',
              sku: handleFor(row),
              options: { Default: 'default' },
              manage_inventory: false,
              prices: [{ amount: priceFor(row), currency_code: 'eur' }],
            },
          ],
          // Round-trips the Kaggle attributes + the river-aligned id so the
          // Medusa adapter on the enrichment side can lift them back out.
          metadata: {
            intentlyId: intentlyIdFor(row),
            gender: row.gender,
            masterCategory: row.masterCategory,
            subCategory: row.subCategory,
            articleType: row.articleType,
            baseColour: row.baseColour,
            season: row.season,
            year: row.year,
            usage: row.usage,
          },
          sales_channels: [{ id: salesChannel.id }],
          category_ids: [catIdByName.get(CATEGORY_BY_ARTICLE[row.articleType] ?? '')].filter(
            (x): x is string => Boolean(x),
          ),
        })),
      },
    })
    created += batch.length
    logger.info(`Seeded batch ${i + 1}/${batches.length} (${created}/${toCreate.length})`)
  }

  logger.info(`Seeded ${created} products`)
}
